/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/background.vue')['default']
    InitHooks: typeof import('./src/components/initHooks.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDivider: typeof import('naive-ui')['NDivider']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NH1: typeof import('naive-ui')['NH1']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NP: typeof import('naive-ui')['NP']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NStatistic: typeof import('naive-ui')['NStatistic']
    Question: typeof import('./src/components/question.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Simple: typeof import('./src/components/CardsComponents/Simple.vue')['default']
    TagTreeSelect: typeof import('./src/components/TagTreeSelect.vue')['default']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VNumberInput: typeof import('vuetify/components')['VNumberInput']
    VProgressLinear: typeof import('vuetify/components')['VProgressLinear']
    VSelect: typeof import('vuetify/components')['VSelect']
    VSheet: typeof import('vuetify/components')['VSheet']
  }
}
