/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/compete/': RouteRecordInfo<'/compete/', '/compete', Record<never, never>, Record<never, never>>,
    '/exam/ongoing.[id]': RouteRecordInfo<'/exam/ongoing.[id]', '/exam/ongoing/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/exam/result.[id]': RouteRecordInfo<'/exam/result.[id]', '/exam/result/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/exam/start': RouteRecordInfo<'/exam/start', '/exam/start', Record<never, never>, Record<never, never>>,
    '/user/signxx': RouteRecordInfo<'/user/signxx', '/user/signxx', Record<never, never>, Record<never, never>>,
  }
}
